### ISSUE TITLE
Compile failed when add HIDL configuration

### ISSUE THREAD

**Issue by wigcheng** [NXPNFCLinux/nxpnfc_android_r#1]
As title, I just add this repo to /vendor/ folder of source code at first, but it shows no entry just like nxpnfc_android_q I asked before:
hwservicemanager: getTransport: Cannot find entry android.hardware.nfc@1.2::INfc/default in either framework or device manifest.

In Android 10, I add relate HIDL setting from your manifest to my device folder's manifest file, it works perfectly!
But I got compile error using this repo as follows:

checkvintf E 03-25 09:26:01    93    93 check_vintf.cpp:554]     vendor.nxp.nxpnfc@1.0::INxpNfc/default
checkvintf E 03-25 09:26:01    93    93 check_vintf.cpp:554] Suggested fix:
checkvintf E 03-25 09:26:01    93    93 check_vintf.cpp:554] 1. Update deprecated HALs to the latest version.
checkvintf E 03-25 09:26:01    93    93 check_vintf.cpp:554] 2. Check for any typos in device manifest or framework compatibility matrices with FCM version >= 5.
checkvintf E 03-25 09:26:01    93    93 check_vintf.cpp:554] 3. For new platform HALs, add them to any framework compatibility matrix with FCM version >= 5 where applicable.
checkvintf E 03-25 09:26:01    93    93 check_vintf.cpp:554] 4. For device-specific HALs, add to DEVICE_FRAMEWORK_COMPATIBILITY_MATRIX_FILE or DEVICE_PRODUCT_COMPATIBILITY_MATRIX_FILE.: Success

Any ideas? Thanks a lot

**Comment by jgeslin** [comment]
Does the /vendor/etc/vintf/manifest.xml file contains the following declaration ?
```
    <hal format="hidl">
        <name>android.hardware.nfc</name>
        <transport>hwbinder</transport>
        <impl level="generic"></impl>
        <version>1.2</version>
        <interface>
            <name>INfc</name>
            <instance>default</instance>
        </interface>
    </hal>

```

**Comment by wigcheng** [comment]
Just checked, no any INfc relate tag. 

I remember Android 10 also has this problem, you can check close issue of nxpnfc_android_q, I need move <source>/vendor/nxp/nfc/manifest.xml content to my device/nxp/xxxx/manifest.xml, then it works.

But in Android 11, the device manifest.xml adapt "Framework compatibility matrix (FCM)" on compile level, so I got error as above.

**Comment by jgeslin** [comment]
> I remember Android 10 also has this problem, you can check close issue of nxpnfc_android_q, I need move /vendor/nxp/nfc/manifest.xml content to my device/nxp/xxxx/manifest.xml, then it works.
As for nxpnfc_android_q, this declaration should be generated according to the below definition from vendor/nxp/nfc/BoardConfigNfc.mk:
`DEVICE_MANIFEST_FILE += vendor/nxp/nfc/manifest.xml`

**Comment by wigcheng** [comment]
In AOSP 11, users need add permission to <source>/hardware/interfaces/compatibility_matrices/<up to your target device CFM version>.xml.
I add INxpNfc tag to xml, finally it works!

Thanks
